Update prompt

diff --git a/home/.config/bash/prompt b/home/.config/bash/prompt
--- a/home/.config/bash/prompt
+++ b/home/.config/bash/prompt
@@ -1,2 +1,27 @@
+# export PS1="\[\e[34m\]\u@\H\[\e[m\] \[\e[32m\]\w\[\e[m\]\n\[\e[31m\]\$(x="\$?"; if [ \$x != 0 ]; then printf '%s\n' \"\$x \";fi)\[\e[m\]❱ "
 
-export PS1="\[\e[34m\]\u@\H\[\e[m\] \[\e[32m\]\w\[\e[m\]\n\[\e[31m\]\$(x="\$?"; if [ \$x != 0 ]; then printf '%s\n' \"\$x \";fi)\[\e[m\]❱ "
+# export PS1="\[\e[34m\]\u@\H\[\e[m\] \[\e[32m\]\w\[\e[m\]\n\[\e[31m\]\$(x="\$?"; if [ \$x != 0 ]; then printf '%s\n' \"\$x \";fi)\[\e[m\]❱ "
+
+PROMPT_COMMAND=__prompt_command    # Function to generate PS1 after CMDs
+
+__prompt_command() {
+    local EXIT="$?"                # This needs to be first
+    PS1=""
+
+    local Reset='\[\e[0m\]'
+
+    local Red='\[\e[0;31m\]'
+    local Green='\[\e[0;32m\]'
+    local Yellow='\[\e[1;33m\]'
+    local Blue='\[\e[1;34m\]'
+    local Purple='\[\e[0;35m\]'
+		local Grey='\[\e[1;30m\]'
+
+		PS1+="${Blue}\u@\h${Reset} \W\n"
+
+    if [ $EXIT != 0 ]; then
+        PS1+="${Red}${EXIT}${Reset} "        # Add red if exit code non 0
+    fi
+
+    PS1+="${Grey}\T${Reset} ❱"
+}
