update prompt

diff --git a/home/.config/bash/prompt b/home/.config/bash/prompt
--- a/home/.config/bash/prompt
+++ b/home/.config/bash/prompt
@@ -1,27 +1,52 @@
-# export PS1="\[\e[34m\]\u@\H\[\e[m\] \[\e[32m\]\w\[\e[m\]\n\[\e[31m\]\$(x="\$?"; if [ \$x != 0 ]; then printf '%s\n' \"\$x \";fi)\[\e[m\]❱ "
+__prompt_command() {
+  local exit="$?"                # This needs to be first
 
-# export PS1="\[\e[34m\]\u@\H\[\e[m\] \[\e[32m\]\w\[\e[m\]\n\[\e[31m\]\$(x="\$?"; if [ \$x != 0 ]; then printf '%s\n' \"\$x \";fi)\[\e[m\]❱ "
+  local txtblk='\e[0;30m' # Black - Regular
+  local txtred='\e[0;31m' # Red
+  local txtgrn='\e[0;32m' # Green
+  local txtylw='\e[0;33m' # Yellow
+  local txtblu='\e[0;34m' # Blue
+  local txtpur='\e[0;35m' # Purple
+  local txtcyn='\e[0;36m' # Cyan
+  local txtwht='\e[0;37m' # White
+  local bldblk='\e[1;30m' # Black - Bold
+  local bldred='\e[1;31m' # Red
+  local bldgrn='\e[1;32m' # Green
+  local bldylw='\e[1;33m' # Yellow
+  local bldblu='\e[1;34m' # Blue
+  local bldpur='\e[1;35m' # Purple
+  local bldcyn='\e[1;36m' # Cyan
+  local bldwht='\e[1;37m' # White
+  local unkblk='\e[4;30m' # Black - Underline
+  local undred='\e[4;31m' # Red
+  local undgrn='\e[4;32m' # Green
+  local undylw='\e[4;33m' # Yellow
+  local undblu='\e[4;34m' # Blue
+  local undpur='\e[4;35m' # Purple
+  local undcyn='\e[4;36m' # Cyan
+  local undwht='\e[4;37m' # White
+  local bakblk='\e[40m'   # Black - Background
+  local bakred='\e[41m'   # Red
+  local bakgrn='\e[42m'   # Green
+  local bakylw='\e[43m'   # Yellow
+  local bakblu='\e[44m'   # Blue
+  local bakpur='\e[45m'   # Purple
+  local bakcyn='\e[46m'   # Cyan
+  local bakwht='\e[47m'   # White
+  local txtrst='\e[0m'    # Text Reset
+
+  # https://robotmoon.com/bash-prompt-generator/
+  local tblu='$(tput setaf 27)'
+  local tcyn='$(tput setaf 23)'
+  local tred='$(tput setaf 124)'
+
+  PS1="${tblu}\u@\h:${tcyn} [\w]${txtrst}\n"
+
+  if [ $exit != 0 ]; then
+    PS1+="${tred}${exit}${txtrst} "        # Add if exit code non 0
+  fi
+
+  PS1+="${bldblk}\t${txtrst} ❱"
+}
 
 PROMPT_COMMAND=__prompt_command    # Function to generate PS1 after CMDs
-
-__prompt_command() {
-    local EXIT="$?"                # This needs to be first
-    PS1=""
-
-    local Reset='\[\e[0m\]'
-
-    local Red='\[\e[0;31m\]'
-    local Green='\[\e[0;32m\]'
-    local Yellow='\[\e[1;33m\]'
-    local Blue='\[\e[1;34m\]'
-    local Purple='\[\e[0;35m\]'
-		local Grey='\[\e[1;30m\]'
-
-		PS1+="${Blue}\u@\h${Reset} \W\n"
-
-    if [ $EXIT != 0 ]; then
-        PS1+="${Red}${EXIT}${Reset} "        # Add red if exit code non 0
-    fi
-
-    PS1+="${Grey}\T${Reset} ❱"
-}
