Refactor for bookworm release

diff --git a/home/.local/bin/backup_drupal b/home/.local/bin/backup_drupal
--- a/home/.local/bin/backup_drupal
+++ b/home/.local/bin/backup_drupal
@@ -4,7 +4,7 @@
 #   Version = 20201117
 #   Ahmed Murad
 #
-# set -x #echo commands
+# set -x #printf '%s\n' commands
 
 #
 # Configuration
@@ -19,16 +19,16 @@ drushbin=/usr/local/bin
 #
 usage() {
   this=$(basename $0)
-  echo
-  echo "USAGE:"
-  echo "$this <options>"
-  echo
-  echo 'Required options:'
-  echo '    -r <string>       Drupal root directory name'
-  echo '    -p <string>       Backup file name prefix (site name)'
-  echo '    -d <string>       Destination directory name'
-  echo '    -a                Archive all files (for non-composer managed sites)'
-  echo
+  printf '%s\n'
+  printf '%s\n' "USAGE:"
+  printf '%s\n' "$this <options>"
+  printf '%s\n'
+  printf '%s\n' 'Required options:'
+  printf '%s\n' '    -r <string>       Drupal root directory name'
+  printf '%s\n' '    -p <string>       Backup file name prefix (site name)'
+  printf '%s\n' '    -d <string>       Destination directory name'
+  printf '%s\n' '    -a                Archive all files (for non-composer managed sites)'
+  printf '%s\n'
   exit 1
 }
 
@@ -50,12 +50,12 @@ while getopts ":r:p:d:a" option; do
       full_backup=true
       ;;
     \?)
-      echo "Invalid option: -$OPTARG" >&2
+      printf '%s\n' "Invalid option: -$OPTARG" >&2
       usage
       exit 1
       ;;
     :)
-      echo "Option -$OPTARG requires an argument" >&2
+      printf '%s\n' "Option -$OPTARG requires an argument" >&2
       usage
       exit 1
       ;;
@@ -70,12 +70,12 @@ if [ -z "$drupal_base" -o -z "$file_prefix" -o -z "$dest_dirname" ]; then
 fi
 
 if [ ! -d $backup_root ]; then
-  echo "ERROR: Backup root $backup_root not found"
+  printf '%s\n' "ERROR: Backup root $backup_root not found"
   exit 2
 fi
 
 if [ ! -d $server_root/$drupal_base ]; then
-  echo "ERROR: Site root $server_root/$drupal_base not found"
+  printf '%s\n' "ERROR: Site root $server_root/$drupal_base not found"
   exit 4
 fi
 
@@ -116,7 +116,7 @@ rotate() {
   fi
 }
 
-echo
+printf '%s\n'
 log ------------ $drupal_base backup started -------------
 
 #
diff --git a/home/.local/bin/backup_wordpress b/home/.local/bin/backup_wordpress
--- a/home/.local/bin/backup_wordpress
+++ b/home/.local/bin/backup_wordpress
@@ -4,7 +4,7 @@
 #   version = 1.2.11
 #   Ahmed Murad
 #
-# set -x #echo commands
+# set -x #printf '%s\n' commands
 
 backup_root=~/backups
 wpcli=/usr/local/bin/wp
@@ -12,15 +12,15 @@ log=true
 
 usage() {
   this=$(basename $0)
-  echo
-  echo "USAGE:"
-  echo "$this <options>"
-  echo
-  echo 'Required options:'
-  echo '  -r <string>    Full path of site root.'
-  echo '  -p <string>    Backup file name prefix.'
-  echo '  -d <string>    Destination directory name.'
-  echo
+  printf '%s\n'
+  printf '%s\n' "USAGE:"
+  printf '%s\n' "$this <options>"
+  printf '%s\n'
+  printf '%s\n' 'Required options:'
+  printf '%s\n' '  -r <string>    Full path of site root.'
+  printf '%s\n' '  -p <string>    Backup file name prefix.'
+  printf '%s\n' '  -d <string>    Destination directory name.'
+  printf '%s\n'
   exit 1
 }
 
@@ -36,12 +36,12 @@ while getopts ":r:p:d:" option; do
     dest_dirname="$OPTARG"
     ;;
   \?)
-    echo "Invalid option: -$OPTARG" >&2
+    printf '%s\n' "Invalid option: -$OPTARG" >&2
     usage
     exit 1
     ;;
   :)
-    echo "Option -$OPTARG requires an argument" >&2
+    printf '%s\n' "Option -$OPTARG requires an argument" >&2
     usage
     exit 1
     ;;
@@ -56,18 +56,18 @@ if [ -z "$site_root" -o -z "$file_prefix" -o -z "$dest_dirname" ]; then
 fi
 
 if [ ! -d $backup_root ]; then
-    echo "ERROR: Backup root $backup_root not found"
+    printf '%s\n' "ERROR: Backup root $backup_root not found"
     exit 2
 fi
 
 if [ ! -d $site_root ]; then
-    echo "ERROR: Site root $site_root not found"
+    printf '%s\n' "ERROR: Site root $site_root not found"
     exit 4
 fi
 
 if ! command -v $wpcli >/dev/null
 then
-  echo "wpcli command not found"
+  printf '%s\n' "wpcli command not found"
 fi
 
 #
@@ -92,7 +92,7 @@ if [ $log = true ]; then
   create_log "${backup_dir}/${file_prefix}_backup.log"
 fi
 
-echo
+printf '%s\n'
 log ------------ $site_root backup started -------------
 
 #
diff --git a/home/.local/bin/chmodw b/home/.local/bin/chmodw
--- a/home/.local/bin/chmodw
+++ b/home/.local/bin/chmodw
@@ -2,7 +2,7 @@
 # set -x
 
 if [[ $EUID -eq 0 ]]; then
-    echo "Do not run as root!"
+    printf '%s\n' "Do not run as root!"
     exit 1
 fi
 
@@ -10,12 +10,12 @@ user=$USER
 group=nginx
 
 usage() {
-    echo "Usage:  ${0##*/} [options] dir"
-    echo "    dir  directory to set permission"
-    echo "    -w   enable group write permission (default: read only)"
-    echo "    -u   user to set as owner (default: $user)"
-    echo "    -g   group (default: $group)"
-    echo "    -h   display this help"
+    printf '%s\n' "Usage:  ${0##*/} [options] dir"
+    printf '%s\n' "    dir  directory to set permission"
+    printf '%s\n' "    -w   enable group write permission (default: read only)"
+    printf '%s\n' "    -u   user to set as owner (default: $user)"
+    printf '%s\n' "    -g   group (default: $group)"
+    printf '%s\n' "    -h   display this help"
     exit 1
 }
 
@@ -27,11 +27,11 @@ while getopts "wu:g:h" option; do
     h) usage ;;
     *) usage ;;
     \?)
-        echo "Unknown option: -$OPTARG" >&2
+        printf '%s\n' "Unknown option: -$OPTARG" >&2
         exit 1
         ;;
     :)
-        echo "Missing option argument for -$OPTARG" >&2
+        printf '%s\n' "Missing option argument for -$OPTARG" >&2
         exit 1
         ;;
     esac
@@ -46,14 +46,14 @@ fi
 if [ -d "$1" ]; then
     dir=$(realpath "$1")
 
-    echo "setting owner to: $user:$group . . ."
+    printf '%s\n' "setting owner to: $user:$group . . ."
     sudo chown -R $user:$group $1
 
-    echo "setting permissions on: ${dir} . . ."
+    printf '%s\n' "setting permissions on: ${dir} . . ."
 
     # {var+x} evaluates to nothing if variable is unset (parameter expansion)
     if [[ ${grpwrite+x} ]] && [[ $grpwrite = 1 ]]; then
-        echo " - enabling group write on: ${dir} . . ."
+        printf '%s\n' " - enabling group write on: ${dir} . . ."
         sudo chmod -R a=rX,ug+w $1
     else
         sudo chmod -R a=rX,u+w $1
@@ -62,5 +62,5 @@ if [ -d "$1" ]; then
     # https://wiki.debian.org/CommonErrorMessages/ArgumentListTooLong
     sudo find $dir -type d -print0 | xargs -0 -n 10 sudo chmod g+s
 else
-    echo "cannot access '${1}': No such file or directory in ${PWD}"
+    printf '%s\n' "cannot access '${1}': No such file or directory in ${PWD}"
 fi
