Convert spaces to tabs

diff --git a/root/user/.local/bin/backup-drupal b/root/user/.local/bin/backup-drupal
--- a/root/user/.local/bin/backup-drupal
+++ b/root/user/.local/bin/backup-drupal
@@ -18,18 +18,18 @@ drushbin=/usr/local/bin
 # Usage help
 #
 usage() {
-  this=$(basename $0)
-  printf '%s\n'
-  printf '%s\n' "USAGE:"
-  printf '%s\n' "$this <options>"
-  printf '%s\n'
-  printf '%s\n' 'Required options:'
-  printf '%s\n' '    -r <string>       Drupal root directory name'
-  printf '%s\n' '    -p <string>       Backup file name prefix (site name)'
-  printf '%s\n' '    -d <string>       Destination directory name'
-  printf '%s\n' '    -a                Archive all files (for non-composer managed sites)'
-  printf '%s\n'
-  exit 1
+	this=$(basename $0)
+	printf '%s\n'
+	printf '%s\n' "USAGE:"
+	printf '%s\n' "$this <options>"
+	printf '%s\n'
+	printf '%s\n' 'Required options:'
+	printf '%s\n' '    -r <string>       Drupal root directory name'
+	printf '%s\n' '    -p <string>       Backup file name prefix (site name)'
+	printf '%s\n' '    -d <string>       Destination directory name'
+	printf '%s\n' '    -a                Archive all files (for non-composer managed sites)'
+	printf '%s\n'
+	exit 1
 }
 
 #
@@ -37,28 +37,28 @@ usage() {
 #
 while getopts ":r:p:d:a" option; do
   case $option in
-    r)
-      drupal_base="$OPTARG"
-      ;;
-    p)
-      file_prefix="$OPTARG"
-      ;;
-    d)
-      dest_dirname="$OPTARG"
-      ;;
-    a)
-      full_backup=true
-      ;;
-    \?)
-      printf '%s\n' "Invalid option: -$OPTARG" >&2
-      usage
-      exit 1
-      ;;
-    :)
-      printf '%s\n' "Option -$OPTARG requires an argument" >&2
-      usage
-      exit 1
-      ;;
+	r)
+		drupal_base="$OPTARG"
+		;;
+	p)
+		file_prefix="$OPTARG"
+		;;
+	d)
+		dest_dirname="$OPTARG"
+		;;
+	a)
+		full_backup=true
+		;;
+	\?)
+		printf '%s\n' "Invalid option: -$OPTARG" >&2
+		usage
+		exit 1
+		;;
+	:)
+		printf '%s\n' "Option -$OPTARG requires an argument" >&2
+		usage
+		exit 1
+		;;
   esac
 done
 
@@ -66,17 +66,17 @@ done
 # Verify options
 #
 if [ -z "$drupal_base" -o -z "$file_prefix" -o -z "$dest_dirname" ]; then
-  usage
+	usage
 fi
 
 if [ ! -d $backup_root ]; then
-  printf '%s\n' "ERROR: Backup root $backup_root not found"
-  exit 2
+	printf '%s\n' "ERROR: Backup root $backup_root not found"
+	exit 2
 fi
 
 if [ ! -d $server_root/$drupal_base ]; then
-  printf '%s\n' "ERROR: Site root $server_root/$drupal_base not found"
-  exit 4
+	printf '%s\n' "ERROR: Site root $server_root/$drupal_base not found"
+	exit 4
 fi
 
 #
@@ -91,29 +91,29 @@ backup_file="${file_prefix}_${timestamp}.tar.zst"
 # Setup log file
 #
 if [ ! -d $backup_dir ]; then
-  mkdir -pv $backup_dir
+	mkdir -pv $backup_dir
 fi
 
 source ~/.local/lib/log.sh
 if [ $log = true ]; then
-  create_log "${backup_dir}/${file_prefix}_backup.log"
+	create_log "${backup_dir}/${file_prefix}_backup.log"
 fi
 
 #
 # Setup rotation function
 #
 rotate() {
-  # delete daily file from 7 days ago and monthly file from  4 months ago
-  olddate_daily=$(date +%Y-%m-%d --date '7 day ago')
-  olddate_daily_day=$(date +%d --date '7 day ago')
-  olddate_monthly=$(date +%Y-%m --date '92 days ago')
-  if [ ! "$olddate_daily_day" == "01" ]; then
-    log "Rotating daily: ${backup_dir}/${file_prefix}_${olddate_daily}*.* ..."
-    find $backup_dir -type f -name "${file_prefix}_${olddate_daily}*.*" -print0 | xargs -0 -n 10 -r rm -v
-  else
-    log "Rotating monthly: ${backup_dir}/${file_prefix}_${olddate_monthly}*.* ..."
-    find $backup_dir -type f -name "${file_prefix}_${olddate_monthly}*.*" -print0 | xargs -0 -n 10 -r rm -v
-  fi
+	# delete daily file from 7 days ago and monthly file from  4 months ago
+	olddate_daily=$(date +%Y-%m-%d --date '7 day ago')
+	olddate_daily_day=$(date +%d --date '7 day ago')
+	olddate_monthly=$(date +%Y-%m --date '92 days ago')
+	if [ ! "$olddate_daily_day" == "01" ]; then
+		log "Rotating daily: ${backup_dir}/${file_prefix}_${olddate_daily}*.* ..."
+		find $backup_dir -type f -name "${file_prefix}_${olddate_daily}*.*" -print0 | xargs -0 -n 10 -r rm -v
+	else
+		log "Rotating monthly: ${backup_dir}/${file_prefix}_${olddate_monthly}*.* ..."
+		find $backup_dir -type f -name "${file_prefix}_${olddate_monthly}*.*" -print0 | xargs -0 -n 10 -r rm -v
+	fi
 }
 
 printf '%s\n'
@@ -126,44 +126,44 @@ database=$($drushbin/drush -r $server_root/$drupal_base sql-connect | cut -d' ' 
 dump_file="${database}_${timestamp}.sql"
 
 if ! $drushbin/drush -r $server_root/$drupal_base sql-dump >$server_root/$dump_file; then
-  log "ERROR: database dump failed ($?)"
-  exit 2
+	log "ERROR: database dump failed ($?)"
+	exit 2
 else
-  log "database dump created: ${server_root}/${dump_file}"
+	log "database dump created: ${server_root}/${dump_file}"
 fi
 
 #
 # Backup files
 #
 if [ "$full_backup" = true ]; then
-  log "archiving all files to: $backup_file"
-  tar --zstd -cf $backup_dir/$backup_file -C $server_root $drupal_base $dump_file
-  status=$?
+	log "archiving all files to: $backup_file"
+	tar --zstd -cf $backup_dir/$backup_file -C $server_root $drupal_base $dump_file
+	status=$?
 else
-  log "archiving site files (excluding core files managed by composer)"
-  tar --zstd -cf $backup_dir/$backup_file --anchored \
-      --exclude=$drupal_base/vendor \
-      --exclude=$drupal_base/web/core \
-      --exclude=$drupal_base/web/modules/contrib \
-      --exclude=$drupal_base/web/profiles \
-      --exclude=$drupal_base/web/themes/contrib \
-      --exclude=$drupal_base/web/.* \
-      --exclude=$drupal_base/web/auto*.php \
-      --exclude=$drupal_base/web/index.php \
-      --exclude=$drupal_base/web/update.php \
-      --exclude=$drupal_base/web/README.txt \
-      -C $server_root $drupal_base $dump_file
-    status=$?
+	log "archiving site files (excluding core files managed by composer)"
+	tar --zstd -cf $backup_dir/$backup_file --anchored \
+		--exclude=$drupal_base/vendor \
+		--exclude=$drupal_base/web/core \
+		--exclude=$drupal_base/web/modules/contrib \
+		--exclude=$drupal_base/web/profiles \
+		--exclude=$drupal_base/web/themes/contrib \
+		--exclude=$drupal_base/web/.* \
+		--exclude=$drupal_base/web/auto*.php \
+		--exclude=$drupal_base/web/index.php \
+		--exclude=$drupal_base/web/update.php \
+		--exclude=$drupal_base/web/README.txt \
+		-C $server_root $drupal_base $dump_file
+	status=$?
 fi
 
 if [ $status -eq 0 ]; then
-  log "archive created: $backup_dir/$backup_file"
-  rotate
+	log "archive created: $backup_dir/$backup_file"
+	rotate
 else
-  log "ERROR: archive failed"
-  exit $status
+	log "ERROR: archive failed"
+	exit $status
 fi
 
 if [ -f $server_root/$dump_file ]; then
-  rm -v $server_root/$dump_file
+	rm -v $server_root/$dump_file
 fi
diff --git a/root/user/.local/bin/backup-wordpress b/root/user/.local/bin/backup-wordpress
--- a/root/user/.local/bin/backup-wordpress
+++ b/root/user/.local/bin/backup-wordpress
@@ -11,63 +11,63 @@ wpcli=/usr/local/bin/wp
 log=true
 
 usage() {
-  this=$(basename $0)
-  printf '%s\n'
-  printf '%s\n' "USAGE:"
-  printf '%s\n' "$this <options>"
-  printf '%s\n'
-  printf '%s\n' 'Required options:'
-  printf '%s\n' '  -r <string>    Full path of site root.'
-  printf '%s\n' '  -p <string>    Backup file name prefix.'
-  printf '%s\n' '  -d <string>    Destination directory name.'
-  printf '%s\n'
-  exit 1
+	this=$(basename $0)
+	printf '%s\n'
+	printf '%s\n' "USAGE:"
+	printf '%s\n' "$this <options>"
+	printf '%s\n'
+	printf '%s\n' 'Required options:'
+	printf '%s\n' '  -r <string>    Full path of site root.'
+	printf '%s\n' '  -p <string>    Backup file name prefix.'
+	printf '%s\n' '  -d <string>    Destination directory name.'
+	printf '%s\n'
+	exit 1
 }
 
 while getopts ":r:p:d:" option; do
-  case $option in
-  r)
-    site_root="$OPTARG"
-    ;;
-  p)
-    file_prefix="$OPTARG"
-    ;;
-  d)
-    dest_dirname="$OPTARG"
-    ;;
-  \?)
-    printf '%s\n' "Invalid option: -$OPTARG" >&2
-    usage
-    exit 1
-    ;;
-  :)
-    printf '%s\n' "Option -$OPTARG requires an argument" >&2
-    usage
-    exit 1
-    ;;
-  esac
+	case $option in
+	r)
+		site_root="$OPTARG"
+		;;
+	p)
+		file_prefix="$OPTARG"
+		;;
+	d)
+		dest_dirname="$OPTARG"
+		;;
+	\?)
+		printf '%s\n' "Invalid option: -$OPTARG" >&2
+		usage
+		exit 1
+		;;
+	:)
+		printf '%s\n' "Option -$OPTARG requires an argument" >&2
+		usage
+		exit 1
+		;;
+	esac
 done
 
 #
 # Verify options
 #
 if [ -z "$site_root" -o -z "$file_prefix" -o -z "$dest_dirname" ]; then
-  usage
+	usage
 fi
 
 if [ ! -d $backup_root ]; then
-    printf '%s\n' "ERROR: Backup root $backup_root not found"
-    exit 2
+	printf '%s\n' "ERROR: Backup root $backup_root not found"
+	exit 2
 fi
 
 if [ ! -d $site_root ]; then
-    printf '%s\n' "ERROR: Site root $site_root not found"
-    exit 4
+	printf '%s\n' "ERROR: Site root $site_root not found"
+	exit 4
 fi
 
 if ! command -v $wpcli >/dev/null
 then
-  printf '%s\n' "wpcli command not found"
+	printf '%s\n' "wpcli command not found"
 fi
 
 #
@@ -84,12 +84,12 @@ wp_root=$site_root/web
 #
 
 if [ ! -d $backup_dir ]; then
-  mkdir -vp $backup_dir
+	mkdir -vp $backup_dir
 fi
 
 source ~/.local/lib/log.sh
 if [ $log = true ]; then
-  create_log "${backup_dir}/${file_prefix}_backup.log"
+	create_log "${backup_dir}/${file_prefix}_backup.log"
 fi
 
 printf '%s\n'
@@ -99,17 +99,17 @@ log ------------ $site_root backup started -------------
 # Setup rotation function
 #
 function rotate() {
-  # delete daily file from 7 days ago and monthly file from  4 months ago
-  olddate_daily=$(date +%Y-%m-%d --date '7 day ago')
-  olddate_daily_day=$(date +%d --date '7 day ago')
-  olddate_monthly=$(date +%Y-%m --date '92 days ago')
-  if [ ! "$olddate_daily_day" == "01" ]; then
-    log "Rotating daily: ${backup_dir}/${file_prefix}_${olddate_daily}*.* ..."
-    find $backup_dir -type f -name "${file_prefix}_${olddate_daily}*.*" -print0 | xargs -0 -n 10 -r rm -v
-  else
-    log "Rotating monthly: ${backup_dir}/${file_prefix}_${olddate_monthly}*.* ..."
-    find $backup_dir -type f -name "${file_prefix}_${olddate_monthly}*.*" -print0 | xargs -0 -n 10 -r rm -v
-  fi
+	# delete daily file from 7 days ago and monthly file from  4 months ago
+	olddate_daily=$(date +%Y-%m-%d --date '7 day ago')
+	olddate_daily_day=$(date +%d --date '7 day ago')
+	olddate_monthly=$(date +%Y-%m --date '92 days ago')
+	if [ ! "$olddate_daily_day" == "01" ]; then
+		log "Rotating daily: ${backup_dir}/${file_prefix}_${olddate_daily}*.* ..."
+		find $backup_dir -type f -name "${file_prefix}_${olddate_daily}*.*" -print0 | xargs -0 -n 10 -r rm -v
+	else
+		log "Rotating monthly: ${backup_dir}/${file_prefix}_${olddate_monthly}*.* ..."
+		find $backup_dir -type f -name "${file_prefix}_${olddate_monthly}*.*" -print0 | xargs -0 -n 10 -r rm -v
+	fi
 }
 
 #
@@ -124,9 +124,9 @@ $wpcli db export --path=$wp_root $site_root/${backup_filename}.sql
 log "Creating archive ..."
 tar --zstd -cf ${backup_dir}/${backup_filename}.tar.zst $(basename $site_root)
 if [ "$?" -eq 0 ]; then
-  log "Success: Archive '${backup_dir}/${backup_filename}.tar.zst' created."
+	log "Success: Archive '${backup_dir}/${backup_filename}.tar.zst' created."
 else
-  log "Error creating archive '${backup_dir}/${backup_filename}.tar.zst'!"
+	log "Error creating archive '${backup_dir}/${backup_filename}.tar.zst'!"
 fi
 
 #
diff --git a/root/user/.local/bin/gen-ssl-localhost b/root/user/.local/bin/gen-ssl-localhost
--- a/root/user/.local/bin/gen-ssl-localhost
+++ b/root/user/.local/bin/gen-ssl-localhost
@@ -3,17 +3,17 @@
 path="/etc/ssl"
 
 if [ "$(whoami)" != "root" ]; then
-  SUDO=sudo
+	SUDO=sudo
 fi
 
 openssl req -x509 -out localhost.crt -keyout localhost.key \
-  -newkey ec:<(openssl ecparam -name secp384r1) -nodes -days 1460\
-  -subj '/CN=localhost' -extensions EXT -config <( \
-   printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
+	-newkey ec:<(openssl ecparam -name secp384r1) -nodes -days 1460\
+	-subj '/CN=localhost' -extensions EXT -config <( \
+	printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
 
 if [ $? -ne 0 ] ; then
-   echo "ERROR: Failed to generate certificate"
-   exit 1
+	echo "ERROR: Failed to generate certificate"
+	exit 1
 fi
 
 ${SUDO} mv localhost.* $path
diff --git a/root/user/.local/bin/sync-backups b/root/user/.local/bin/sync-backups
--- a/root/user/.local/bin/sync-backups
+++ b/root/user/.local/bin/sync-backups
@@ -15,8 +15,8 @@ create_log $log_file
 log '-----'
 
 if [ ! -d ${dest_dir}/ ]; then
-    log "ERROR: $dest_dir does not exist"
-    exit 1
+	log "ERROR: $dest_dir does not exist"
+	exit 1
 fi
 
 rsync -a --delete --log-file=${log_file} sadmin@soundvision.com:backups/ ${dest_dir}/
diff --git a/root/user/.local/bin/upgrade-civicrm b/root/user/.local/bin/upgrade-civicrm
--- a/root/user/.local/bin/upgrade-civicrm
+++ b/root/user/.local/bin/upgrade-civicrm
@@ -2,14 +2,14 @@
 # set -x
 
 if [ -z "$1" ]; then
-    printf '%s\n' "CiviCRM version number missing"
-    exit 1
+	printf '%s\n' "CiviCRM version number missing"
+	exit 1
 fi
 
 printf '%s\n' 'Checking installation directory . . .'
 if [ ! -d ./sites ]; then
-    printf '%s\n' "run from site root directory"
-    exit 1
+	printf '%s\n' "run from site root directory"
+	exit 1
 fi
 
 download_dir=~/dev
@@ -17,11 +17,11 @@ civicrm_file="civicrm-${1}-drupal.tar.gz"
 
 printf '%s\n' 'Downloading CiviCRM . . .'
 if [ ! -f $download_dir/$civicrm_file ]; then
-    wget -q https://download.civicrm.org/$civicrm_file -P "$download_dir/"
-    if [ $? -ne 0 ]; then
-        printf '%s\n' "download failed for $civicrm_file"
-        exit 1
-    fi
+	wget -q https://download.civicrm.org/$civicrm_file -P "$download_dir/"
+	if [ $? -ne 0 ]; then
+		printf '%s\n' "download failed for $civicrm_file"
+		exit 1
+	fi
 fi
 
 printf '%s\n' 'Backing up site . . .'
diff --git a/root/user/.local/bin/upgrade-civicrm-wordpress b/root/user/.local/bin/upgrade-civicrm-wordpress
--- a/root/user/.local/bin/upgrade-civicrm-wordpress
+++ b/root/user/.local/bin/upgrade-civicrm-wordpress
@@ -2,24 +2,24 @@
 set -x
 
 if [ -z "$1" ]; then
-    printf '%s\n' "CiviCRM version number missing"
-    exit 1
+	printf '%s\n' "CiviCRM version number missing"
+	exit 1
 fi
 
 download_dir=~/dev
 civicrm_file="civicrm-${1}-wordpress.zip"
 
 if [ ! -d ./wp-content ]; then
-    printf '%s\n' "run from site root directory"
-    exit 1
+	printf '%s\n' "run from site root directory"
+	exit 1
 fi
 
 if [ ! -f $download_dir/$civicrm_file ]; then
-    wget -q https://download.civicrm.org/$civicrm_file -P "$download_dir/"
-    if [ $? -ne 0 ]; then
-        printf '%s\n' "download failed for $civicrm_file"
-        exit 1
-    fi
+	wget -q https://download.civicrm.org/$civicrm_file -P "$download_dir/"
+	if [ $? -ne 0 ]; then
+		printf '%s\n' "download failed for $civicrm_file"
+		exit 1
+	fi
 fi
 
 sudo rm -rf wp-content/plugins/civicrm
